"""empty message

Revision ID: 15e96c5d8a4
Revises: 35f92a4f83e
Create Date: 2019-01-14 00:57:51.245800

"""

# revision identifiers, used by Alembic.
revision = '15e96c5d8a4'
down_revision = '35f92a4f83e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidaturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_vaga', sa.Integer(), nullable=False),
    sa.Column('id_pessoa', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_pessoa'], ['pessoas.id'], ),
    sa.ForeignKeyConstraint(['id_vaga'], ['vagas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidaturas')
    ### end Alembic commands ###
